global using MediatR;
global using Application.DTOs;
global using Domain.Entities;
global using Domain.Interface;
global using Application.Interface;
global using Application.Model;
global using Application.Helpers;
global using Application.Services;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Configuration;
global using System.Text;
global using Application.CQRS.Commands.Users;
global using Application.BackgroundServices;
global using Application.Provider;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using Domain.Common;
global using Application.Interface.Hubs;
global using Application.Interface.SearchAI;
global using Application.Model.Events;
global using Microsoft.Extensions.Hosting;
global using Application.Common;
global using Application.Interface.Api;

global using static Domain.Common.Enums;
global using Application.DTOs.Message;
global using Application.Interface.ContextSerivce;
global using static Domain.Common.Helper;
