import os
from dotenv import load_dotenv

load_dotenv()

SQL_SERVER_CONNECTION = os.getenv("SQL_SERVER_CONNECTION")
# MISTRAL_MODEL_PATH = os.getenv("MISTRAL_MODEL_PATH")
GOOGLE_API_KEY_LLM = os.getenv("GOOGLE_API_KEY_LLM")
GOOGLE_API_KEY_SQL = os.getenv("GOOGLE_API_KEY_SQL")
GOOGLE_API_KEY_QUERY = os.getenv("GOOGLE_API_KEY_QUERY")
NETCORE_API_URL = os.getenv("NETCORE_API_URL")
FE_API_URL = os.getenv("FE_API_URL")
SIGNALR_HUB_URL = os.getenv("SIGNALR_HUB_URL")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
GOOGLE_API_KEY_FIX_SQL = os.getenv("GOOGLE_API_KEY_FIX_SQL")
print(f"NETCORE_API_URL: {NETCORE_API_URL}")
print(f"SIGNALR_HUB_URL: {SIGNALR_HUB_URL}")
